name: Dispatcher 
on: 
  push:
    branches: [main]
jobs: 
  dispatch: 
    name: Dispatch 
    runs-on: ubuntu-latest 
    steps:           
      - name: Fire Dispatc Event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.doc-pat}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bjornna/bjornna.github.io/dispatches \
            -d '{"event_type":"dispatch-event"}'
  
        
